SHOW WAREHOUSES;
USE WAREHOUSE COMPUTE_WH;
SHOW DATABASES;
SELECT CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF100;

-- 4. Implementing Feature Engineering with Snowflake & Feature Store  
-- • Extract: Use Snowflake SQL to fetch raw data. 

SELECT * 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER
LIMIT 10;

-- Extract only key fields from the ORDERS table

SELECT O_ORDERKEY, O_CUSTKEY, O_ORDERDATE, O_TOTALPRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS
LIMIT 10;

-- Join CUSTOMER and NATION tables to extract customer country info

SELECT 
    C.C_NAME,
    N.N_NAME AS COUNTRY,
    C.C_ACCTBAL
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER AS C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
    ON C.C_NATIONKEY = N.N_NATIONKEY
LIMIT 10;

-- Q. Transform: Perform feature engineering (aggregations, encoding, etc.).  
-- Aggregation — Average Order Value per Customer

SELECT 
    O.O_CUSTKEY AS CUSTOMER_ID,
    AVG(O.O_TOTALPRICE) AS AVG_ORDER_VALUE,
    COUNT(O.O_ORDERKEY) AS TOTAL_ORDERS
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS AS O
GROUP BY O.O_CUSTKEY
ORDER BY AVG_ORDER_VALUE DESC
LIMIT 10;

-- eg. Create Revenue Feature — Total Spend per Customer

SELECT 
    O.O_CUSTKEY AS CUSTOMER_ID,
    SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)) AS TOTAL_SPEND
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS AS O
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM AS L
    ON O.O_ORDERKEY = L.L_ORDERKEY
GROUP BY O.O_CUSTKEY
ORDER BY TOTAL_SPEND DESC
LIMIT 10;


-- eg.Encoding — Map Nation to Region

SELECT 
    N.N_NAME AS NATION,
    R.R_NAME AS REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION AS R
    ON N.N_REGIONKEY = R.R_REGIONKEY;

-- eg. Derived Feature — Average Discount per Nation

SELECT 
    N.N_NAME AS NATION,
    AVG(L.L_DISCOUNT) AS AVG_DISCOUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM AS L
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS AS O
    ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER AS C
    ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION AS N
    ON C.C_NATIONKEY = N.N_NATIONKEY
GROUP BY N.N_NAME
ORDER BY AVG_DISCOUNT DESC;


-- Q.Load into Feature Store: Explain how features can be stored in a Feature Store  


USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS FEATURE_STORE_DB;
CREATE SCHEMA IF NOT EXISTS FEATURE_STORE_DB.FEATURES;

SHOW DATABASES LIKE 'FEATURE_STORE_DB';
SHOW SCHEMAS IN DATABASE FEATURE_STORE_DB;

USE DATABASE FEATURE_STORE_DB;
USE SCHEMA FEATURES;

CREATE OR REPLACE TABLE CUSTOMER_FEATURES AS
SELECT 
    O.O_CUSTKEY AS CUSTOMER_ID,
    AVG(O.O_TOTALPRICE) AS AVG_ORDER_VALUE,
    COUNT(O.O_ORDERKEY) AS TOTAL_ORDERS
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS AS O
GROUP BY O.O_CUSTKEY;

SELECT * FROM CUSTOMER_FEATURES LIMIT 10;
